### ISSUE TITLE
Issue_W

### ISSUE THREAD

**Issue by bumfuzzlemeldrop** [ayushnighoskar/Spotify-Clone#1]
Hello there!
I have found some issues in the code of "index.html" -
1. Empty alt attributes in <img alt="1" /> tag.
2. Duplicate alt="1" in multiple <img /> tags.
3. Missing image sources for <img> tags.
4. Incorrect closing span tag format – Some </span> tags have extra spaces (e.g., </span >).
5. Unclear purpose of songlistplay and timestamp spans – Might need additional context or CSS adjustments.
6. No <form> element for email input (if any intended).
7. Missing aria-labels or accessibility attributes for better screen reader support.
Can I contribute to your repository?

**Comment by ayushnighoskar** [comment]
Please feel free to open a pull request with any improvements or fixes you have in mind.
